// <auto-generated />
using System;
using Client_On_Boarding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_On_Boarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409171623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client_On_Boarding.Models.BusinessIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinessIndustries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4794),
                            CreatedBy = 0,
                            IndustryName = "Rice Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4797)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4798),
                            CreatedBy = 0,
                            IndustryName = "Medical Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4798)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4799),
                            CreatedBy = 0,
                            IndustryName = "Electronics",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4799)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4800),
                            CreatedBy = 0,
                            IndustryName = "Restaurant",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4800)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<int>("LeadSourceID")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("LeadStatusID");

                    b.HasIndex("PriorityId");

                    b.ToTable("ClientLeads");
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh",
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4908),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4908)
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "India",
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4910),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4910)
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Pakistan",
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4911),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4911)
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Sri Lanka",
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4912),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4912)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4964),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4965),
                            PriorityName = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4966),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4966),
                            PriorityName = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4967),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4967),
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LeadSourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeadSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4928),
                            CreatedBy = 0,
                            LeadSourceName = "Referral",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4928)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4929),
                            CreatedBy = 0,
                            LeadSourceName = "Website",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4929)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4930),
                            CreatedBy = 0,
                            LeadSourceName = "LinkedIn",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4930)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4931),
                            CreatedBy = 0,
                            LeadSourceName = "Cold Call",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4932)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4947),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4947),
                            StatusName = "New"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4948),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4949),
                            StatusName = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4949),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4950),
                            StatusName = "Follow-up"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4950),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 9, 17, 16, 22, 999, DateTimeKind.Utc).AddTicks(4951),
                            StatusName = "Active"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.HasOne("Client_On_Boarding.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.BusinessIndustry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadStatus", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("LeadStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.Navigation("Country");

                    b.Navigation("Industry");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Priority");
                });
#pragma warning restore 612, 618
        }
    }
}
