// <auto-generated />
using System;
using Client_On_Boarding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_On_Boarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524183146_BillingOrSubcriptionMap_ClientLead")]
    partial class BillingOrSubcriptionMap_ClientLead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client_On_Boarding.Models.BillingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BillingCycle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingName = "Monthly",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7525),
                            CreatedBy = 0,
                            DiscountPercentage = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7526)
                        },
                        new
                        {
                            Id = 2,
                            BillingName = "Quarterly ",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7527),
                            CreatedBy = 0,
                            DiscountPercentage = 10,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7527)
                        },
                        new
                        {
                            Id = 3,
                            BillingName = "Yearly",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7529),
                            CreatedBy = 0,
                            DiscountPercentage = 25,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7529)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.BusinessIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinessIndustries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7085),
                            CreatedBy = 0,
                            IndustryName = "Rice Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7089)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7092),
                            CreatedBy = 0,
                            IndustryName = "Medical Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7093)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7094),
                            CreatedBy = 0,
                            IndustryName = "Electronics",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7095)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7096),
                            CreatedBy = 0,
                            IndustryName = "Restaurant",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7096)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillingCycleId")
                        .HasColumnType("int");

                    b.Property<int?>("BillingId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadSourceID")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubscriptionPlainId")
                        .HasColumnType("int");

                    b.Property<int?>("SubsrcriptionId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillingCycleId");

                    b.HasIndex("CountryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("LeadStatusID");

                    b.HasIndex("PriorityId");

                    b.HasIndex("SubscriptionPlainId");

                    b.ToTable("ClientLeads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hyderabad",
                            ClientName = "By Default",
                            CompanyName = "Software Company",
                            CountryId = 3,
                            CreateDate = new DateTime(2026, 5, 24, 11, 31, 45, 881, DateTimeKind.Local).AddTicks(7426),
                            CreatedBy = 0,
                            IndustryId = 3,
                            LeadSourceID = 3,
                            LeadStatusID = 4,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7416),
                            Notes = "",
                            PhoneNo = "",
                            PhotoPath = "",
                            PostalCode = "",
                            PriorityId = 2,
                            Province = "",
                            StreetAddress = ""
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientPageAllowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClientPageAllowances");
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7241)
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "India",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7242),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7243)
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Pakistan",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7244),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7244)
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Sri Lanka",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7245),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7246)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ERPModules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModuleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErpModules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7549),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7550),
                            ModuleName = "Accounting"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7394),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7394),
                            PriorityName = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7396),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7396),
                            PriorityName = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7397),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7397),
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LeadSourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeadSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7335),
                            CreatedBy = 0,
                            LeadSourceName = "Referral",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7336)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7337),
                            CreatedBy = 0,
                            LeadSourceName = "Website",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7338)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7339),
                            CreatedBy = 0,
                            LeadSourceName = "LinkedIn",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7339)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7340),
                            CreatedBy = 0,
                            LeadSourceName = "Cold Call",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7340)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7367),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7367),
                            StatusName = "New"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7369),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7369),
                            StatusName = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7371),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7371),
                            StatusName = "Follow-up"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7372),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7373),
                            StatusName = "Active"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7587),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7588),
                            PageName = "Products"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7589),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7589),
                            PageName = "Customers"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7590),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7591),
                            PageName = "Vendors"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7592),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7592),
                            PageName = "Bank Accounts"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7593),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7593),
                            PageName = "Opening Cash"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7594),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7594),
                            PageName = "General Journal Voucher"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7595),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7596),
                            PageName = "Master Configuration"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7597),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7597),
                            PageName = "Orders"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7598),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7598),
                            PageName = "Invoices"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7599),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7599),
                            PageName = "Receipt"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7600),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7601),
                            PageName = "Sale Return"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7601),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7602),
                            PageName = "Purchase Invoices"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7603),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7603),
                            PageName = "Payment"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7604),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7604),
                            PageName = "Purchase Return"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7605),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7606),
                            PageName = "Cash Billing"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7606),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7607),
                            PageName = "Counter Sale Return"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7608),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7608),
                            PageName = "Expenses"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7609),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7609),
                            PageName = "Stock Adjustment"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7610),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7610),
                            PageName = "Rollback"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7611),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7612),
                            PageName = "Customer Balance"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7612),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7613),
                            PageName = "Vendor Balance"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7614),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7614),
                            PageName = "Bank Balance"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7615),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7615),
                            PageName = "Stock Report"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7616),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7617),
                            PageName = "Customer Ledger"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7618),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7618),
                            PageName = "Vendor Ledger"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7619),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7619),
                            PageName = "Bank/Cash Ledger"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7620),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7620),
                            PageName = "Expenses Reports"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7621),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7622),
                            PageName = "Overall Daily Report"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.PagesFieldSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PageFieldSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7663),
                            CreatedBy = 0,
                            FieldName = "Product Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7663),
                            PageId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7668),
                            CreatedBy = 0,
                            FieldName = "Company",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7668),
                            PageId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7670),
                            CreatedBy = 0,
                            FieldName = "Category",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7670),
                            PageId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7672),
                            CreatedBy = 0,
                            FieldName = "Main Unit",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7673),
                            PageId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7674),
                            CreatedBy = 0,
                            FieldName = "Has Alternate Unit?",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7674),
                            PageId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7678),
                            CreatedBy = 0,
                            FieldName = "Purchase Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7678),
                            PageId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7679),
                            CreatedBy = 0,
                            FieldName = "Sales Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7680),
                            PageId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7681),
                            CreatedBy = 0,
                            FieldName = "Opening Stock",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7681),
                            PageId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7683),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7683),
                            PageId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7684),
                            CreatedBy = 0,
                            FieldName = "Customer Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7684),
                            PageId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7686),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7686),
                            PageId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7687),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7688),
                            PageId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7689),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7689),
                            PageId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7738),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7739),
                            PageId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7740),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7741),
                            PageId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7742),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7742),
                            PageId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7744),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7744),
                            PageId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7745),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7746),
                            PageId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7747),
                            CreatedBy = 0,
                            FieldName = "Vendor Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7747),
                            PageId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7749),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7749),
                            PageId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7750),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7751),
                            PageId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7752),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7752),
                            PageId = 3
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7754),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7754),
                            PageId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7755),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7756),
                            PageId = 3
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7757),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7757),
                            PageId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7758),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7759),
                            PageId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7760),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7760),
                            PageId = 3
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7762),
                            CreatedBy = 0,
                            FieldName = "Bank Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7762),
                            PageId = 4
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7763),
                            CreatedBy = 0,
                            FieldName = "Account Holder",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7764),
                            PageId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7765),
                            CreatedBy = 0,
                            FieldName = "Account No",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7765),
                            PageId = 4
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7767),
                            CreatedBy = 0,
                            FieldName = "Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7767),
                            PageId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7768),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7769),
                            PageId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7770),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7770),
                            PageId = 4
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.SubscriptionPlain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComaSeperated_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlainName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlain");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComaSeperated_Description = "Single User,Single Branch",
                            CreateDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7567),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 24, 18, 31, 45, 881, DateTimeKind.Utc).AddTicks(7568),
                            PlainName = "Starter"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.HasOne("Client_On_Boarding.Models.BillingCycle", "BillingCycle")
                        .WithMany("ClientLeads")
                        .HasForeignKey("BillingCycleId");

                    b.HasOne("Client_On_Boarding.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.BusinessIndustry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadStatus", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("LeadStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.HasOne("Client_On_Boarding.Models.SubscriptionPlain", "SubscriptionPlain")
                        .WithMany("ClientLeads")
                        .HasForeignKey("SubscriptionPlainId");

                    b.Navigation("BillingCycle");

                    b.Navigation("Country");

                    b.Navigation("Industry");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Priority");

                    b.Navigation("SubscriptionPlain");
                });

            modelBuilder.Entity("Client_On_Boarding.Models.BillingCycle", b =>
                {
                    b.Navigation("ClientLeads");
                });

            modelBuilder.Entity("Client_On_Boarding.Models.SubscriptionPlain", b =>
                {
                    b.Navigation("ClientLeads");
                });
#pragma warning restore 612, 618
        }
    }
}
