// <auto-generated />
using System;
using Client_On_Boarding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_On_Boarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517074023_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client_On_Boarding.Models.BusinessIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinessIndustries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1112),
                            CreatedBy = 0,
                            IndustryName = "Rice Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1115)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1121),
                            CreatedBy = 0,
                            IndustryName = "Medical Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1121)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1122),
                            CreatedBy = 0,
                            IndustryName = "Electronics",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1123)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1124),
                            CreatedBy = 0,
                            IndustryName = "Restaurant",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1124)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<int>("LeadSourceID")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("LeadStatusID");

                    b.HasIndex("PriorityId");

                    b.ToTable("ClientLeads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hyderabad",
                            ClientName = "By Default",
                            CompanyName = "Software Company",
                            CountryId = 3,
                            CreateDate = new DateTime(2026, 5, 17, 0, 40, 22, 694, DateTimeKind.Local).AddTicks(1372),
                            CreatedBy = 0,
                            IndustryId = 3,
                            LeadSourceID = 3,
                            LeadStatusID = 4,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1363),
                            Notes = "",
                            PhoneNo = "",
                            PhotoPath = "",
                            PostalCode = "",
                            PriorityId = 2,
                            Province = "",
                            StreetAddress = ""
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientPageAllowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClientPageAllowances");
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh",
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1262),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1263)
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "India",
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1264),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1265)
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Pakistan",
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1266),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1266)
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Sri Lanka",
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1267),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1268)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1339),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1339),
                            PriorityName = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1340),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1341),
                            PriorityName = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1342),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1342),
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LeadSourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeadSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1289),
                            CreatedBy = 0,
                            LeadSourceName = "Referral",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1289)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1291),
                            CreatedBy = 0,
                            LeadSourceName = "Website",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1291)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1292),
                            CreatedBy = 0,
                            LeadSourceName = "LinkedIn",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1292)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1293),
                            CreatedBy = 0,
                            LeadSourceName = "Cold Call",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1294)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1314),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1314),
                            StatusName = "New"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1316),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1316),
                            StatusName = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1317),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1317),
                            StatusName = "Follow-up"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1318),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1319),
                            StatusName = "Active"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1477),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1477),
                            PageName = "Products"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1479),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1479),
                            PageName = "Customers"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1480),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1480),
                            PageName = "Vendors"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1481),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1482),
                            PageName = "Bank Accounts"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1483),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1483),
                            PageName = "Opening Cash"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1484),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1484),
                            PageName = "General Journal Voucher"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1485),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1485),
                            PageName = "Master Configuration"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1486),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1486),
                            PageName = "Orders"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1487),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1488),
                            PageName = "Invoices"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1488),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1489),
                            PageName = "Receipt"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1490),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1490),
                            PageName = "Sale Return"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1491),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1491),
                            PageName = "Purchase Invoices"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1492),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1492),
                            PageName = "Payment"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1493),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1493),
                            PageName = "Purchase Return"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1494),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1495),
                            PageName = "Cash Billing"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1495),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1496),
                            PageName = "Counter Sale Return"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1497),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1497),
                            PageName = "Expenses"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1498),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1498),
                            PageName = "Stock Adjustment"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1499),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1499),
                            PageName = "Rollback"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1500),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1501),
                            PageName = "Customer Balance"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1501),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1502),
                            PageName = "Vendor Balance"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1503),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1503),
                            PageName = "Bank Balance"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1504),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1504),
                            PageName = "Stock Report"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1505),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1505),
                            PageName = "Customer Ledger"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1513),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1513),
                            PageName = "Vendor Ledger"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1515),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1515),
                            PageName = "Bank/Cash Ledger"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1516),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1516),
                            PageName = "Expenses Reports"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1517),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1517),
                            PageName = "Overall Daily Report"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.PagesFieldSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PageFieldSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1612),
                            CreatedBy = 0,
                            FieldName = "Product Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1612),
                            PageId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1615),
                            CreatedBy = 0,
                            FieldName = "Company",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1615),
                            PageId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1617),
                            CreatedBy = 0,
                            FieldName = "Category",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1618),
                            PageId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1619),
                            CreatedBy = 0,
                            FieldName = "Main Unit",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1619),
                            PageId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1620),
                            CreatedBy = 0,
                            FieldName = "Has Alternate Unit?",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1621),
                            PageId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1622),
                            CreatedBy = 0,
                            FieldName = "Purchase Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1622),
                            PageId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1624),
                            CreatedBy = 0,
                            FieldName = "Sales Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1624),
                            PageId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1625),
                            CreatedBy = 0,
                            FieldName = "Opening Stock",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1626),
                            PageId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1627),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1627),
                            PageId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1629),
                            CreatedBy = 0,
                            FieldName = "Customer Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1629),
                            PageId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1631),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1632),
                            PageId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1633),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1633),
                            PageId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1634),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1635),
                            PageId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1636),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1636),
                            PageId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1638),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1639),
                            PageId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1640),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1640),
                            PageId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1642),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1642),
                            PageId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1643),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1643),
                            PageId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1645),
                            CreatedBy = 0,
                            FieldName = "Vendor Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1645),
                            PageId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1646),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1647),
                            PageId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1648),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1648),
                            PageId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1649),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1650),
                            PageId = 3
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1651),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1651),
                            PageId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1652),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1653),
                            PageId = 3
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1654),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1654),
                            PageId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1656),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1656),
                            PageId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1658),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1658),
                            PageId = 3
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1660),
                            CreatedBy = 0,
                            FieldName = "Bank Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1660),
                            PageId = 4
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1661),
                            CreatedBy = 0,
                            FieldName = "Account Holder",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1662),
                            PageId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1663),
                            CreatedBy = 0,
                            FieldName = "Account No",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1663),
                            PageId = 4
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1665),
                            CreatedBy = 0,
                            FieldName = "Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1665),
                            PageId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1666),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1666),
                            PageId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1668),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 17, 7, 40, 22, 694, DateTimeKind.Utc).AddTicks(1668),
                            PageId = 4
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.HasOne("Client_On_Boarding.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.BusinessIndustry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadStatus", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("LeadStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.Navigation("Country");

                    b.Navigation("Industry");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Priority");
                });
#pragma warning restore 612, 618
        }
    }
}
