// <auto-generated />
using System;
using Client_On_Boarding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_On_Boarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523094142_add_Subscription_ErpModels_BillingCycle")]
    partial class add_Subscription_ErpModels_BillingCycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client_On_Boarding.Models.BillingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BillingCycle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingName = "Monthly",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9280),
                            CreatedBy = 0,
                            DiscountPercentage = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9281)
                        },
                        new
                        {
                            Id = 2,
                            BillingName = "Quarterly ",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9282),
                            CreatedBy = 0,
                            DiscountPercentage = 10,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9282)
                        },
                        new
                        {
                            Id = 3,
                            BillingName = "Yearly",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9283),
                            CreatedBy = 0,
                            DiscountPercentage = 25,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9283)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.BusinessIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinessIndustries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8926),
                            CreatedBy = 0,
                            IndustryName = "Rice Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8930)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8933),
                            CreatedBy = 0,
                            IndustryName = "Medical Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8933)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8934),
                            CreatedBy = 0,
                            IndustryName = "Electronics",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8935)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8935),
                            CreatedBy = 0,
                            IndustryName = "Restaurant",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(8936)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadSourceID")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("LeadStatusID");

                    b.HasIndex("PriorityId");

                    b.ToTable("ClientLeads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hyderabad",
                            ClientName = "By Default",
                            CompanyName = "Software Company",
                            CountryId = 3,
                            CreateDate = new DateTime(2026, 5, 23, 2, 41, 37, 267, DateTimeKind.Local).AddTicks(9182),
                            CreatedBy = 0,
                            IndustryId = 3,
                            LeadSourceID = 3,
                            LeadStatusID = 4,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9173),
                            Notes = "",
                            PhoneNo = "",
                            PhotoPath = "",
                            PostalCode = "",
                            PriorityId = 2,
                            Province = "",
                            StreetAddress = ""
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientPageAllowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClientPageAllowances");
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9059),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9059)
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "India",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9084),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9085)
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Pakistan",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9086),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9086)
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Sri Lanka",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9087),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9087)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ERPModules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModuleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErpModules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9299),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9300),
                            ModuleName = "Accounting"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9153),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9154),
                            PriorityName = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9155),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9155),
                            PriorityName = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9156),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9156),
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LeadSourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeadSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9103),
                            CreatedBy = 0,
                            LeadSourceName = "Referral",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9103)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9104),
                            CreatedBy = 0,
                            LeadSourceName = "Website",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9104)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9105),
                            CreatedBy = 0,
                            LeadSourceName = "LinkedIn",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9105)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9106),
                            CreatedBy = 0,
                            LeadSourceName = "Cold Call",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9106)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9127),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9128),
                            StatusName = "New"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9129),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9129),
                            StatusName = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9130),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9130),
                            StatusName = "Follow-up"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9131),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9131),
                            StatusName = "Active"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9332),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9332),
                            PageName = "Products"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9333),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9333),
                            PageName = "Customers"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9334),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9334),
                            PageName = "Vendors"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9335),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9335),
                            PageName = "Bank Accounts"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9336),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9336),
                            PageName = "Opening Cash"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9337),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9337),
                            PageName = "General Journal Voucher"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9337),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9338),
                            PageName = "Master Configuration"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9338),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9339),
                            PageName = "Orders"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9339),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9339),
                            PageName = "Invoices"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9340),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9340),
                            PageName = "Receipt"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9341),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9341),
                            PageName = "Sale Return"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9342),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9342),
                            PageName = "Purchase Invoices"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9343),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9343),
                            PageName = "Payment"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9344),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9344),
                            PageName = "Purchase Return"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9344),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9345),
                            PageName = "Cash Billing"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9345),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9345),
                            PageName = "Counter Sale Return"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9346),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9346),
                            PageName = "Expenses"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9347),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9347),
                            PageName = "Stock Adjustment"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9348),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9348),
                            PageName = "Rollback"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9349),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9349),
                            PageName = "Customer Balance"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9349),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9350),
                            PageName = "Vendor Balance"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9350),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9351),
                            PageName = "Bank Balance"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9351),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9351),
                            PageName = "Stock Report"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9352),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9352),
                            PageName = "Customer Ledger"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9353),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9353),
                            PageName = "Vendor Ledger"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9354),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9354),
                            PageName = "Bank/Cash Ledger"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9355),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9355),
                            PageName = "Expenses Reports"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9355),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9356),
                            PageName = "Overall Daily Report"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.PagesFieldSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PageFieldSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9383),
                            CreatedBy = 0,
                            FieldName = "Product Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9383),
                            PageId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9385),
                            CreatedBy = 0,
                            FieldName = "Company",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9385),
                            PageId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9386),
                            CreatedBy = 0,
                            FieldName = "Category",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9386),
                            PageId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9387),
                            CreatedBy = 0,
                            FieldName = "Main Unit",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9388),
                            PageId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9388),
                            CreatedBy = 0,
                            FieldName = "Has Alternate Unit?",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9389),
                            PageId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9429),
                            CreatedBy = 0,
                            FieldName = "Purchase Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9429),
                            PageId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9430),
                            CreatedBy = 0,
                            FieldName = "Sales Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9430),
                            PageId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9431),
                            CreatedBy = 0,
                            FieldName = "Opening Stock",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9432),
                            PageId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9433),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9433),
                            PageId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9434),
                            CreatedBy = 0,
                            FieldName = "Customer Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9434),
                            PageId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9435),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9435),
                            PageId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9436),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9436),
                            PageId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9437),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9437),
                            PageId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9438),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9439),
                            PageId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9439),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9440),
                            PageId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9441),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9441),
                            PageId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9442),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9442),
                            PageId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9443),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9443),
                            PageId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9444),
                            CreatedBy = 0,
                            FieldName = "Vendor Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9444),
                            PageId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9445),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9445),
                            PageId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9446),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9446),
                            PageId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9447),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9448),
                            PageId = 3
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9448),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9449),
                            PageId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9450),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9450),
                            PageId = 3
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9451),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9451),
                            PageId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9452),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9452),
                            PageId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9453),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9453),
                            PageId = 3
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9454),
                            CreatedBy = 0,
                            FieldName = "Bank Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9454),
                            PageId = 4
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9455),
                            CreatedBy = 0,
                            FieldName = "Account Holder",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9456),
                            PageId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9456),
                            CreatedBy = 0,
                            FieldName = "Account No",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9457),
                            PageId = 4
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9458),
                            CreatedBy = 0,
                            FieldName = "Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9458),
                            PageId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9459),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9459),
                            PageId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9460),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9460),
                            PageId = 4
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.SubscriptionPlain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComaSeperated_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlainName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlain");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0m,
                            ComaSeperated_Description = "Single User,Single Branch",
                            CreateDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9318),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 5, 23, 9, 41, 37, 267, DateTimeKind.Utc).AddTicks(9318),
                            PlainName = "Starter"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.HasOne("Client_On_Boarding.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.BusinessIndustry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadStatus", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("LeadStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.Navigation("Country");

                    b.Navigation("Industry");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Priority");
                });
#pragma warning restore 612, 618
        }
    }
}
