// <auto-generated />
using System;
using Client_On_Boarding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_On_Boarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410220629_PageAllowances")]
    partial class PageAllowances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client_On_Boarding.Models.BusinessIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinessIndustries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4968),
                            CreatedBy = 0,
                            IndustryName = "Rice Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4972)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4975),
                            CreatedBy = 0,
                            IndustryName = "Medical Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4975)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4976),
                            CreatedBy = 0,
                            IndustryName = "Electronics",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4976)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4977),
                            CreatedBy = 0,
                            IndustryName = "Restaurant",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(4977)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<int>("LeadSourceID")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("LeadStatusID");

                    b.HasIndex("PriorityId");

                    b.ToTable("ClientLeads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hyderabad",
                            ClientName = "By Default",
                            CompanyName = "Software Company",
                            CountryId = 3,
                            CreateDate = new DateTime(2026, 4, 11, 3, 6, 29, 237, DateTimeKind.Local).AddTicks(5188),
                            CreatedBy = 0,
                            IndustryId = 3,
                            LeadSourceID = 3,
                            LeadStatusID = 4,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5179),
                            Notes = "",
                            PhoneNo = "",
                            PhotoPath = "",
                            PostalCode = "",
                            PriorityId = 2,
                            Province = "",
                            StreetAddress = ""
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh",
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5103),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5104)
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "India",
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5105),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5105)
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Pakistan",
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5106),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5106)
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Sri Lanka",
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5107),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5107)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5162),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5162),
                            PriorityName = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5163),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5163),
                            PriorityName = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5164),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5164),
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LeadSourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeadSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5125),
                            CreatedBy = 0,
                            LeadSourceName = "Referral",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5125)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5126),
                            CreatedBy = 0,
                            LeadSourceName = "Website",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5127)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5127),
                            CreatedBy = 0,
                            LeadSourceName = "LinkedIn",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5128)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5128),
                            CreatedBy = 0,
                            LeadSourceName = "Cold Call",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5129)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5144),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5144),
                            StatusName = "New"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5145),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5145),
                            StatusName = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5146),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5146),
                            StatusName = "Follow-up"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5147),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5147),
                            StatusName = "Active"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5245),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5246),
                            PageName = "Products"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5283),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5284),
                            PageName = "Customers"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5285),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5285),
                            PageName = "Vendors"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5286),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5286),
                            PageName = "Bank Accounts"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5287),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5287),
                            PageName = "Opening Cash"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5288),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5288),
                            PageName = "General Journal Voucher"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5289),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5289),
                            PageName = "Master Configuration"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5290),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5290),
                            PageName = "Orders"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5291),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5291),
                            PageName = "Invoices"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5292),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5292),
                            PageName = "Receipt"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5292),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5293),
                            PageName = "Sale Return"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5293),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5294),
                            PageName = "Purchase Invoices"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5294),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5295),
                            PageName = "Payment"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5295),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5296),
                            PageName = "Purchase Return"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5296),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5297),
                            PageName = "Cash Billing"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5297),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5298),
                            PageName = "Counter Sale Return"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5298),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5298),
                            PageName = "Expenses"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5299),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5299),
                            PageName = "Stock Adjustment"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5300),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5300),
                            PageName = "Rollback"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5301),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5301),
                            PageName = "Customer Balance"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5302),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5302),
                            PageName = "Vendor Balance"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5303),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5303),
                            PageName = "Bank Balance"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5304),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5304),
                            PageName = "Stock Report"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5305),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5305),
                            PageName = "Customer Ledger"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5305),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5306),
                            PageName = "Vendor Ledger"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5306),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5307),
                            PageName = "Bank/Cash Ledger"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5307),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5308),
                            PageName = "Expenses Reports"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5308),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5309),
                            PageName = "Overall Daily Report"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.PagesFieldSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PageFieldSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5339),
                            CreatedBy = 0,
                            FieldName = "Product Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5340),
                            PageId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5341),
                            CreatedBy = 0,
                            FieldName = "Company",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5341),
                            PageId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5343),
                            CreatedBy = 0,
                            FieldName = "Category",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5343),
                            PageId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5344),
                            CreatedBy = 0,
                            FieldName = "Main Unit",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5344),
                            PageId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5345),
                            CreatedBy = 0,
                            FieldName = "Has Alternate Unit?",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5346),
                            PageId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5347),
                            CreatedBy = 0,
                            FieldName = "Purchase Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5347),
                            PageId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5348),
                            CreatedBy = 0,
                            FieldName = "Sales Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5348),
                            PageId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5349),
                            CreatedBy = 0,
                            FieldName = "Opening Stock",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5349),
                            PageId = 1
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5350),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5351),
                            PageId = 1
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5351),
                            CreatedBy = 0,
                            FieldName = "Customer Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5352),
                            PageId = 2
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5353),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5353),
                            PageId = 2
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5354),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5354),
                            PageId = 2
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5355),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5355),
                            PageId = 2
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5356),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5357),
                            PageId = 2
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5357),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5358),
                            PageId = 2
                        },
                        new
                        {
                            Id = 16,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5359),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5359),
                            PageId = 2
                        },
                        new
                        {
                            Id = 17,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5360),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5360),
                            PageId = 2
                        },
                        new
                        {
                            Id = 18,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5361),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5361),
                            PageId = 2
                        },
                        new
                        {
                            Id = 19,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5362),
                            CreatedBy = 0,
                            FieldName = "Vendor Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5363),
                            PageId = 3
                        },
                        new
                        {
                            Id = 20,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5364),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5364),
                            PageId = 3
                        },
                        new
                        {
                            Id = 21,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5365),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5365),
                            PageId = 3
                        },
                        new
                        {
                            Id = 22,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5366),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5366),
                            PageId = 3
                        },
                        new
                        {
                            Id = 23,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5367),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5367),
                            PageId = 3
                        },
                        new
                        {
                            Id = 24,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5368),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5369),
                            PageId = 3
                        },
                        new
                        {
                            Id = 25,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5370),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5370),
                            PageId = 3
                        },
                        new
                        {
                            Id = 26,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5371),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5371),
                            PageId = 3
                        },
                        new
                        {
                            Id = 27,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5372),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5372),
                            PageId = 3
                        },
                        new
                        {
                            Id = 28,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5373),
                            CreatedBy = 0,
                            FieldName = "Bank Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5374),
                            PageId = 4
                        },
                        new
                        {
                            Id = 29,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5375),
                            CreatedBy = 0,
                            FieldName = "Account Holder",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5375),
                            PageId = 4
                        },
                        new
                        {
                            Id = 30,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5376),
                            CreatedBy = 0,
                            FieldName = "Account No",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5376),
                            PageId = 4
                        },
                        new
                        {
                            Id = 31,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5377),
                            CreatedBy = 0,
                            FieldName = "Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5377),
                            PageId = 4
                        },
                        new
                        {
                            Id = 32,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5378),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5378),
                            PageId = 4
                        },
                        new
                        {
                            Id = 33,
                            ClientId = 0,
                            CreateDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5379),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 10, 22, 6, 29, 237, DateTimeKind.Utc).AddTicks(5380),
                            PageId = 4
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.HasOne("Client_On_Boarding.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.BusinessIndustry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadStatus", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("LeadStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.Navigation("Country");

                    b.Navigation("Industry");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Priority");
                });
#pragma warning restore 612, 618
        }
    }
}
