// <auto-generated />
using System;
using Client_On_Boarding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_On_Boarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client_On_Boarding.Models.BusinessIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinessIndustries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(948),
                            CreatedBy = 0,
                            IndustryName = "Rice Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(968)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(971),
                            CreatedBy = 0,
                            IndustryName = "Medical Wholesaler",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(971)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(972),
                            CreatedBy = 0,
                            IndustryName = "Electronics",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(972)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(973),
                            CreatedBy = 0,
                            IndustryName = "Restaurant",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(974)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<int>("LeadSourceID")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("LeadStatusID");

                    b.HasIndex("PriorityId");

                    b.ToTable("ClientLeads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hyderabad",
                            ClientName = "By Default",
                            CompanyName = "Software Company",
                            CountryId = 3,
                            CreateDate = new DateTime(2026, 4, 12, 3, 29, 18, 371, DateTimeKind.Local).AddTicks(1230),
                            CreatedBy = 0,
                            IndustryId = 3,
                            LeadSourceID = 3,
                            LeadStatusID = 4,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1218),
                            Notes = "",
                            PhoneNo = "",
                            PhotoPath = "",
                            PostalCode = "",
                            PriorityId = 2,
                            Province = "",
                            StreetAddress = ""
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientPageAllowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClientPageAllowances");
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh",
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1129),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1129)
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "India",
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1130),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1130)
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Pakistan",
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1131),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1132)
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Sri Lanka",
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1132),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1133)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1198),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1199),
                            PriorityName = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1200),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1200),
                            PriorityName = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1201),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1201),
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LeadSourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeadSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1152),
                            CreatedBy = 0,
                            LeadSourceName = "Referral",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1153)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1154),
                            CreatedBy = 0,
                            LeadSourceName = "Website",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1154)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1155),
                            CreatedBy = 0,
                            LeadSourceName = "LinkedIn",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1155)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1156),
                            CreatedBy = 0,
                            LeadSourceName = "Cold Call",
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1156)
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1176),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1176),
                            StatusName = "New"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1177),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1177),
                            StatusName = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1178),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1178),
                            StatusName = "Follow-up"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1179),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1180),
                            StatusName = "Active"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1319),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1319),
                            PageName = "Products"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1321),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1321),
                            PageName = "Customers"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1322),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1322),
                            PageName = "Vendors"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1323),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1323),
                            PageName = "Bank Accounts"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1324),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1324),
                            PageName = "Opening Cash"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1325),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1325),
                            PageName = "General Journal Voucher"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1326),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1326),
                            PageName = "Master Configuration"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1327),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1327),
                            PageName = "Orders"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1328),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1328),
                            PageName = "Invoices"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1329),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1329),
                            PageName = "Receipt"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1333),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1333),
                            PageName = "Sale Return"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1334),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1334),
                            PageName = "Purchase Invoices"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1335),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1335),
                            PageName = "Payment"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1336),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1336),
                            PageName = "Purchase Return"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1337),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1337),
                            PageName = "Cash Billing"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1338),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1338),
                            PageName = "Counter Sale Return"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1338),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1339),
                            PageName = "Expenses"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1339),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1340),
                            PageName = "Stock Adjustment"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1340),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1341),
                            PageName = "Rollback"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1341),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1342),
                            PageName = "Customer Balance"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1342),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1343),
                            PageName = "Vendor Balance"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1343),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1343),
                            PageName = "Bank Balance"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1344),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1344),
                            PageName = "Stock Report"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1345),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1345),
                            PageName = "Customer Ledger"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1388),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1388),
                            PageName = "Vendor Ledger"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1389),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1389),
                            PageName = "Bank/Cash Ledger"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1390),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1390),
                            PageName = "Expenses Reports"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1391),
                            CreatedBy = 0,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1391),
                            PageName = "Overall Daily Report"
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.PagesFieldSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.Property<int>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PageFieldSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1425),
                            CreatedBy = 0,
                            FieldName = "Product Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1426),
                            PageId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1428),
                            CreatedBy = 0,
                            FieldName = "Company",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1428),
                            PageId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1429),
                            CreatedBy = 0,
                            FieldName = "Category",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1429),
                            PageId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1430),
                            CreatedBy = 0,
                            FieldName = "Main Unit",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1431),
                            PageId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1432),
                            CreatedBy = 0,
                            FieldName = "Has Alternate Unit?",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1432),
                            PageId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1433),
                            CreatedBy = 0,
                            FieldName = "Purchase Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1433),
                            PageId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1434),
                            CreatedBy = 0,
                            FieldName = "Sales Rate",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1434),
                            PageId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1435),
                            CreatedBy = 0,
                            FieldName = "Opening Stock",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1436),
                            PageId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1437),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1437),
                            PageId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1438),
                            CreatedBy = 0,
                            FieldName = "Customer Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1438),
                            PageId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1446),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1447),
                            PageId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1448),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1448),
                            PageId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1449),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1449),
                            PageId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1450),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1450),
                            PageId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1451),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1452),
                            PageId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1453),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1453),
                            PageId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1454),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1454),
                            PageId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1455),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1455),
                            PageId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1456),
                            CreatedBy = 0,
                            FieldName = "Vendor Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1457),
                            PageId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1458),
                            CreatedBy = 0,
                            FieldName = "City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1458),
                            PageId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1459),
                            CreatedBy = 0,
                            FieldName = "Area By City",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1459),
                            PageId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1460),
                            CreatedBy = 0,
                            FieldName = "Full Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1460),
                            PageId = 3
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1461),
                            CreatedBy = 0,
                            FieldName = "Office Phone",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1462),
                            PageId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1463),
                            CreatedBy = 0,
                            FieldName = "Contact No 1",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1463),
                            PageId = 3
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1464),
                            CreatedBy = 0,
                            FieldName = "Contact No 2",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1464),
                            PageId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1465),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1465),
                            PageId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1466),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1467),
                            PageId = 3
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1468),
                            CreatedBy = 0,
                            FieldName = "Bank Name",
                            IsRequired = true,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1469),
                            PageId = 4
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1470),
                            CreatedBy = 0,
                            FieldName = "Account Holder",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1471),
                            PageId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1472),
                            CreatedBy = 0,
                            FieldName = "Account No",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1472),
                            PageId = 4
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1475),
                            CreatedBy = 0,
                            FieldName = "Address",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1475),
                            PageId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1479),
                            CreatedBy = 0,
                            FieldName = "Opening Balance",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1479),
                            PageId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1481),
                            CreatedBy = 0,
                            FieldName = "Active",
                            IsRequired = false,
                            IsView = true,
                            ModifyBy = 0,
                            ModifyDate = new DateTime(2026, 4, 11, 22, 29, 18, 371, DateTimeKind.Utc).AddTicks(1481),
                            PageId = 4
                        });
                });

            modelBuilder.Entity("Client_On_Boarding.Models.ClientLead", b =>
                {
                    b.HasOne("Client_On_Boarding.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.BusinessIndustry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadStatus", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("LeadStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client_On_Boarding.Models.LeadPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.Navigation("Country");

                    b.Navigation("Industry");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Priority");
                });
#pragma warning restore 612, 618
        }
    }
}
